# List of curvatures to test in the fan
test_curvs_m = [-0.9, -0.7, -0.5, -0.3, -0.1, 0.0, 0.1, 0.3, 0.5, 0.7, 0.9]

# List of headings to test, 90, and 45 deg to left and right, plus straight ahead
test_heads_rad = [-1.57079632679, -0.78539816339, 0.0, 0.78539816339, 1.57079632679]

# Separation of points within the paths
path_point_separation_m = 0.1

# Weight the path at 1.0, equal to the alignment cost
heuristic_remaining_cost_weight = 1.0

# Equal weighting with remaining path cost
heuristic_alignment_cost_weight = 1.0

# Distance to the target which we will accept as reaching the target
target_tolerance_m = 0.1

max_path_length_m = 1.0
min_path_length_m = 0.5