# List of curvatures to test in the fan
test_curvs_m = [-0.9, -0.7, -0.5, -0.3, -0.1, 0.0, 0.1, 0.3, 0.5, 0.7, 0.9]

# Separation of points within the paths
path_point_separation_m = 0.1

# Weight the path at 1.0, equal to the alignment cost
heuristic_remaining_cost_weight = 1.0

# Equal weighting with remaining path cost
heuristic_alignment_cost_weight = 1.0

# Distance to the target which we will accept as reaching the target
target_tolerance_m = 0.25