# Basic dependabot config to keep our dependencies up to date

version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/*"
    schedule:
      interval: "daily"
    target-branch: "dev"
    reviewers:
      - "duncanrhamill"
