#!/bin/bash

MULTICAST_IP=224.1.1.1

gst-launch-1.0 udpsrc multicast-group=$MULTICAST_IP port=5000 ! \
    application/x-rtp,encoding-name=JPEG,payload=26 ! \
    queue ! rtpjpegdepay ! jpegdec ! \
    autovideosink