#!/bin/bash

MULTICAST_IP=224.1.1.1

gst-launch-1.0 v4l2src device=/dev/video0 ! \
    video/x-raw,width=640,height=480 ! \
    queue ! jpegenc ! rtpjpegpay ! \
    queue ! udpsink host=$MULTICAST_IP port=5000 