name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev, arch_rework ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
